global:
  network: rinkeby

polygon-nft-listener:
  environments:
    DEBUG: true
  livenessProbe:
    initialDelaySeconds: 360s
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

polygon-gateway:
  service:
    nodePort: 30217


logging:
  logstash:
    tcp-socket:
      enabled: true
      destinations: logstash:4560
  logfmt:
    enabled: false
