common:
  chain-id: 3
  node-type: GETH
  sudo-swap-addresses:
    pair-factory-v1: "0x1af70c6e674b09d58a55c8fedc7578b59938ec6c"
    exponential-curve-v1: "0xf21A52a9eBeb480267eBc4C8d14Cb1d59889A392"
    linear-curve-v1: "0x7aa8EC1028D36883bb3a94D2a04B5cf0D8231d26"
rarible:
  ethereum:
    max-frame-size: 10485760
listener:
  load-open-sea-orders: false
