common:
  node-type: GETH
  open-sea-nonce-increment: 1
  # TODO PT-1243
  currency-contract-addresses:
    weth: "0xc778417e063141139fce010982780140aa0cd5ab"
  sudo-swap-addresses:
    pair-factory-v1: "0x25b4efc43c9dcae134233cd577ffca7cfad6748f"
    exponential-curve-v1: "0x0d807bd5ff2c4ef298755be30e22926b33244b0c"
    linear-curve-v1: "0xac6dcff6e13132f075e36ca3a7f403236f869438"
  feature-flags:
    showSudoSwapOrdersWithOtherPlatforms: true
  publish:
    publishAmmOrders: true
rarible:
  opensea:
    testnet: true
  seaport:
    testnet: true
  looksrare:
    testnet: true

listener:
  openSeaEndpoint: ${rarible.opensea.endpoint}
  seaport-load:
    enabled: true
    save-enabled: true
