common:
  chain-id: 4
  node-type: GETH
  open-sea-nonce-increment: 1

rarible:
  opensea:
    testnet: true

listener:
  openSeaEndpoint: ${rarible.opensea.endpoint}

logging:
  logstash:
    tcp-socket:
      enabled: true
      destinations: logstash:4560
  logfmt:
    enabled: false
