global:
  network: rinkeby

ethereum-nft-listener:
  livenessProbe:
    initialDelaySeconds: 360s
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

ethereum-gateway:
  service:
    nodePort: 30216

logging:
  logstash:
    tcp-socket:
      enabled: true
      destinations: logstash:4560
  logfmt:
    enabled: false